package com.smartcall.guard.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF3F51B5)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBE1FF)
val LightOnPrimaryContainer = Color(0xFF001452)
val LightSecondary = Color(0xFF585E71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDCE2F9)
val LightOnSecondaryContainer = Color(0xFF151B2C)
val LightTertiary = Color(0xFF735572)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFED7FA)
val LightOnTertiaryContainer = Color(0xFF2A132C)
val LightBackground = Color(0xFFFEFBFF)
val LightOnBackground = Color(0xFF1B1B1F)
val LightSurface = Color(0xFFFEFBFF)
val LightOnSurface = Color(0xFF1B1B1F)
val LightSurfaceVariant = Color(0xFFE2E2EC)
val LightOnSurfaceVariant = Color(0xFF45464F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOutline = Color(0xFF757680)

val DarkPrimary = Color(0xFFB4C5FF)
val DarkOnPrimary = Color(0xFF002484)
val DarkPrimaryContainer = Color(0xFF223E9B)
val DarkOnPrimaryContainer = Color(0xFFDBE1FF)
val DarkSecondary = Color(0xFFC0C6DD)
val DarkOnSecondary = Color(0xFF2A3042)
val DarkSecondaryContainer = Color(0xFF404659)
val DarkOnSecondaryContainer = Color(0xFFDCE2F9)
val DarkTertiary = Color(0xFFE1BBDD)
val DarkOnTertiary = Color(0xFF422742)
val DarkTertiaryContainer = Color(0xFF5A3C5A)
val DarkOnTertiaryContainer = Color(0xFFFED7FA)
val DarkBackground = Color(0xFF1B1B1F)
val DarkOnBackground = Color(0xFFE4E2E6)
val DarkSurface = Color(0xFF1B1B1F)
val DarkOnSurface = Color(0xFFE4E2E6)
val DarkSurfaceVariant = Color(0xFF45464F)
val DarkOnSurfaceVariant = Color(0xFFC6C6D0)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOutline = Color(0xFF90909A)

val LightColorScheme = androidx.compose.material3.lightColorScheme(
    primary = LightPrimary,
    onPrimary = LightOnPrimary,
    primaryContainer = LightPrimaryContainer,
    onPrimaryContainer = LightOnPrimaryContainer,
    secondary = LightSecondary,
    onSecondary = LightOnSecondary,
    secondaryContainer = LightSecondaryContainer,
    onSecondaryContainer = LightOnSecondaryContainer,
    tertiary = LightTertiary,
    onTertiary = LightOnTertiary,
    tertiaryContainer = LightTertiaryContainer,
    onTertiaryContainer = LightOnTertiaryContainer,
    background = LightBackground,
    onBackground = LightOnBackground,
    surface = LightSurface,
    onSurface = LightOnSurface,
    surfaceVariant = LightSurfaceVariant,
    onSurfaceVariant = LightOnSurfaceVariant,
    error = LightError,
    onError = LightOnError,
    errorContainer = LightErrorContainer,
    outline = LightOutline
)

val DarkColorScheme = androidx.compose.material3.darkColorScheme(
    primary = DarkPrimary,
    onPrimary = DarkOnPrimary,
    primaryContainer = DarkPrimaryContainer,
    onPrimaryContainer = DarkOnPrimaryContainer,
    secondary = DarkSecondary,
    onSecondary = DarkOnSecondary,
    secondaryContainer = DarkSecondaryContainer,
    onSecondaryContainer = DarkOnSecondaryContainer,
    tertiary = DarkTertiary,
    onTertiary = DarkOnTertiary,
    tertiaryContainer = DarkTertiaryContainer,
    onTertiaryContainer = DarkOnTertiaryContainer,
    background = DarkBackground,
    onBackground = DarkOnBackground,
    surface = DarkSurface,
    onSurface = DarkOnSurface,
    surfaceVariant = DarkSurfaceVariant,
    onSurfaceVariant = DarkOnSurfaceVariant,
    error = DarkError,
    onError = DarkOnError,
    errorContainer = DarkErrorContainer,
    outline = DarkOutline
)
